### ISSUE TITLE
As a vscode user I would like to see the imdone board in vscode so I can get shit done!   

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-core#132]
----
*opened via [imdone.io](https://imdone.io) from a code comment on [657ce9e8](https://github.com/imdone/imdone-core/commit/657ce9e8) by Jesse jesse@piascik.net*

----

https://github.com/imdone/imdone-core/blob/3746f83fc150302d63d2322dc706dd831ae86ab0/README.md#L179-L184

**Comment by dwuttke90** [comment]
would also love to see the imdone board as a vscode extension. any time eta for it?

**Comment by piascikj** [comment]
I don't plan to implement a vscode extension, but I did just release a stand alone version for macOS.  You can download it from [imdone.io](https://imdone.io) and documentation can be found [here](https://imdone.io/docs).

I've been using it as I build it and like it better than having the board as a tab in atom because it's easier to switch to my kanban view with the keyboard and I have all my boards in one place regardless of where I edit the files.

Right now it's a 7 day trial, but I'm considering a free version that allows only one project to be open at a time.
