### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andradei** [imdone/imdone-core#14]
- imdone version: 1.1.39
- OS: OS X 10.10.5
- Atom version: 1.0.19

I'm adding comments inline and on top of code like so `// TODO Test todo` and it doesn't show when pressing `ctrl + shift + T`. Sometimes it shows the TODO area with no items in it.

In order to get it working I need to do `// # TODO:1 Test todo` and it doesn't work for all TODOs I make.

Some screenshots of what I'm facing:

![code1](https://cloud.githubusercontent.com/assets/2653546/10179383/d552dcae-66c2-11e5-99df-485fe46775ff.jpg)
![code2](https://cloud.githubusercontent.com/assets/2653546/10179384/d5678618-66c2-11e5-8e9f-1a21d362352d.jpg)

**Comment by piascikj** [comment]
Looks like we need to add groovy to languages.  I'll let you know when it's been updated.

**Comment by piascikj** [comment]
@andradei The groovy language has been added.  Please try again and let me know if it's working for you.

**Comment by andradei** [comment]
I can confirm it is working. Thank you for the plugin!

**Comment by piascikj** [comment]
You're welcome!
