### ISSUE TITLE
FEATURE REQUEST: Add Kotlin support

### ISSUE THREAD

**Issue by dwuttke90** [imdone/imdone-core#145]
add Kotlin support. shouldn't be too hard since its pretty similar to java. especially the comments should be the same.

EDIT:
added
`".kt": { "name": "kotlin", "symbol": "//", "block": cBlock },`
to the languages.js. and it seems to work quite fine so far.

**Comment by piascikj** [comment]
Implemented in [imdone 1.4.0](https://imdone.io)
