### ISSUE TITLE
Not all paths from .gitignore are omitted

### ISSUE THREAD

**Issue by feimosi** [imdone/imdone-core#16]
I'm not sure why is that happening, but the plugin enters one of the folders that is included inside the `.gitignore` file. It's called `test-output`, to be exact. Maybe the dash is a problem? For `node_modules`, `.tmp`, `java/target` etc. it works fine.

**Comment by piascikj** [comment]
Thanks for reporting.  Moving this one up in priority.

**Comment by piascikj** [comment]
How is this working now?  I made a change a while back that replaced the globbing library imdone uses.

**Comment by feimosi** [comment]
I've changed the project and development environment since then. Also not using Atom anymore so I can't verify it. Please do it yourself and close the issue if considered resolved.
