### ISSUE TITLE
todos in block comments

### ISSUE THREAD

**Issue by mrmechko** [imdone/imdone-core#18]
Currently, the following doesn't work:

```
/**
  * TODO: something
  */
```

In order for this to be identified, you need to add a double slash or something:

```
/**
  * //TODO: something
  */
```

Which means a large amount of code written by others won't list todo's etc.  Would it be possible to include todo's listed in comment blocks?

**Comment by piascikj** [comment]
What is the file extension?  Code blocks work, but the extension must be configured in languages.js

**Comment by mrmechko** [comment]
Languages are `scala` and `sbt`.  sent a pull request.

**Comment by piascikj** [comment]
Thanks, I'll get that in now.

**Comment by piascikj** [comment]
@mrmechko It's in imdone-atom 1.2.6.  Thanks for the PR!

**Comment by mrmechko** [comment]
great! thanks for the fast response.  Just gonna say, I'd love to see `imdone` as a stand-alone `electron` app.
