### ISSUE TITLE
Allowing the Emoji Toolbar plugin's emoji to be used in `+Tags`

### ISSUE THREAD

**Issue by SkepticMystic** [imdone/imdone-core#236]
Hey sax! Adding an issue so that the emoji from the Obsidian plugin "Emoji Toolbar" can be used as imdone tags again 🙂 

Here is an issue on the plugin's repo asking about the character encoding used in the emoji: https://github.com/oliveryh/obsidian-emoji-toolbar/issues/12

**Comment by piascikj** [comment]
@SkepticMystic Can this be closed?  Unless I'm mistaken it was fixed in [Release 1.17.3](https://imdone.io/docs/#/changelog?id=_1173).

**Comment by SkepticMystic** [comment]
Indeed, this is working!
