### ISSUE TITLE
TODO in markdown files are not recognized

### ISSUE THREAD

**Issue by mgrenier** [imdone/imdone-core#28]
```
Windows 10
Atom 1.3.2
imdone-atom 1.3.18
imdone-core 1.2.42
```

TODO in markdown files are not recognized due to the symbol being `""` in [lib/languages.js](https://github.com/imdone/imdone-core/blob/master/lib/languages.js#L28).

Added to my `.imdone/config.json` :
```
"languages": {
  ".md": {
    "name": "markdown",
    "symbol": "-"
  }
}
```

and prepended all my TODO with `- ` :
```
- IDEA sinaps.core : PM2 cluster
- IDEA sinaps.core : HTTP/2
```

and now it's working like expected (showing in the Task panel)

**Comment by piascikj** [comment]
What you did is great if it works for you :+1:   The reason for the lack of comment symbol in markdown is due to it being a text formatting syntax.  If you use the HASH or LINK task syntax anywhere in your markdown, imdone will pick it up.
