### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by Kosai106** [imdone/imdone-core#30]
I'm not getting any error message or warning, but whenever I drag 'n drop an item from the main TODO category to a new one (In this case called JQueryUI) the items simply disappear.

They're still found in the code, but imdone stops finding them at all.

Again, I'm not getting any error messages, so I can't really say more than this.
All I can tell you is that I used JQueryUI and wanted to move their TODO's to a new category when I discovered the issue.

If there's anything else I can do from my end, please let me know.

Cheers,
Kevin Østerkilde

**Comment by piascikj** [comment]
I experienced this the other day, and noticed it was introduced when I changed the file watcher implementation.  I'm committing and releasing a fix shortly, but you may also benefit from using [.imdoneignore](https://github.com/imdone/imdone-atom#ignoring-files) to ignore unwanted tasks from third part libs.

**Comment by piascikj** [comment]
Give 1.3.25 a shot and let me know how it works for you.

**Comment by Kosai106** [comment]
Just updated and sadly it still seems to be happening.
Good tip about .imdoneignore, however being able to move notes around seems to be a big selling point for the extension.

**Comment by piascikj** [comment]
Just cloned jquery-ui and wow they're comments are all over the place in terms of style.  I'll have to dig a bit deeper into this to see what's happening.

**Comment by Kosai106** [comment]
For todays test, I just made a

```
//NOTE: Test
```

and it still disappeard when moved to a new column, so it's not just JqueryUI comments.

(Though I do agree with you - Their comments are wild.)

**Comment by piascikj** [comment]
That is strange.  But the list name changes in the code, right?  Can you post your `.imdone/config.json` and the name of the list you created?

**Comment by Kosai106** [comment]
Yeah, it changes as it's supposed to, it just disappears from the list.

The list used here was called "Test".

```
{
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|dist|logs)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],
  "watcher": true,
  "keepEmptyPriority": false,
  "code": {
    "include_lists": [
      "TODO",
      "DOING",
      "DONE",
      "PLANNING",
      "FIXME",
      "ARCHIVE",
      "HACK",
      "CHANGED",
      "XXX",
      "IDEA",
      "NOTE",
      "REVIEW"
    ]
  },
  "lists": [
    {
      "name": "NOTE",
      "hidden": false
    },
    {
      "name": "TODO",
      "hidden": false
    },
    {
      "name": "Test",
      "hidden": false
    }
  ],
  "marked": {
    "gfm": true,
    "tables": true,
    "breaks": false,
    "pedantic": false,
    "smartLists": true,
    "langPrefix": "language-"
  }
}
```

**Comment by piascikj** [comment]
This is for sure a bug.  Try renaming the list to `TEST` all caps, then move the task in.  Because your list name is mixed case and the task is in a code comment, it should be putting a `#` in front, but I suspect it's not.  The all caps version should work until we get the bug fixed.  Let me know if that does it.

**Comment by Kosai106** [comment]
@piascikj Renaming the list to all caps fixed the issue. :+1:
