### ISSUE TITLE
Velocity Double Hash does not work

### ISSUE THREAD

**Issue by Wintercypher** [imdone/imdone-core#36]
Hello!

Love the package but sadly the comment styles of Velocity are currently not supported. It would be amazing if I could customize the comment styles to support additional languages. 

Velocity uses
##Single

#*
Multi Line
*#

**Comment by piascikj** [comment]
What are the file extensions for velocity templates?

**Comment by Wintercypher** [comment]
Velocity uses .vm

**Comment by piascikj** [comment]
This should be in the latest release!
