### ISSUE TITLE
Session manage my browser windows and tabs

### ISSUE THREAD

**Issue by Worros** [imdone/imdone-core#37]
I have no idea if this is doable, or useful for anyone but me.

Before you continue - count how many browser windows and tabs you have open right now. 

Problem background: 
- My habit when I note a term/concept/software/whatever that I intend-to/should look at is to middle click to a new tab.
- I'd keep work, project and personal in a couple of different browser windows, and that worked. I tend to accumulate tabs  and purge every couple of days (often finding duplicate pages) 
- I try to avoid opening my laptop unless all my screens are attached as re-arranging browser, editor and console sessions merged to a single workspace from 3 Virt-desktops * 3 screens is painful.

Problem
-  I'm doing 2 code projects where I'm on a steep learning curve, a couple of personal projects, work and then had to do a theme review - My number of browser windows jumped from 6-8ish with < 10 tabs each to at > 200 tabs across X browser windows. I've lost all control and its driving me to distraction.

Solution??? - Being able to close associated browser windows down when I close out my IDE (or switch projects!), and open them back up in place would be awesome. Having a record of various documents I reviewed that I could correlate to a changeset in 12 months sounds pretty useful too. ("I implemented it that way because I read an article somewhere..."

**Comment by piascikj** [comment]
Not sure this is the right place for your issue.  Maybe in a atom package forum?

**Comment by Contemptable** [comment]
I had a vision of linking a project with an ongoing browser session.

It could also work for specific TODO's. Something like 'Start connected browser session for this TODO' 

Feature request was on my mind while I was playing with your plugin, I needed to braindump/vent - I'm obviously happy for you to close :)

**Comment by Worros** [comment]
I had a vision of linking a project with an ongoing browser session.

It could also work for specific TODO's. Something like 'Start connected browser session for this TODO' 

Feature request was on my mind while I was playing with your plugin, I needed to braindump/vent - I'm obviously happy for you to close :)

**Comment by piascikj** [comment]
No worries!  Thanks for the idea.
