### ISSUE TITLE
Where is config file?

### ISSUE THREAD

**Issue by martindsouza** [imdone/imdone-core#4]
I'd like to enhance the TODOs to handle `.pks` and `.pkb` files for Oracle. Where is `.imdone/config.json` located? When I went to `~/.atom/` I didn't see it there.

**Comment by piascikj** [comment]
It's at the root of your project, but that isn't where this needs to be added.  I should probably allow it there as well, but right now it's in  [imdone-core/lib/languages.js](https://github.com/imdone/imdone-core/blob/master/lib/languages.js).

I'll get them added tonight, but I'll add an issue for an enhancement.

**Comment by martindsouza** [comment]
Thanks for adding.
