### ISSUE TITLE
Omit Tags From Task Names

### ISSUE THREAD

**Issue by SolarLune** [imdone/imdone-core#50]
Whoops, didn't mean to send this. Anyway, the issue is that tasks that contain tags using the `+` character also contain that text as the task name itself. For example, I have `Fix coloring problems +Easy` as a name on one of my tasks; it seems like the `+Easy` could be omitted, since it's a tag.

Anyway, great work on this - it's really awesome!

**Comment by piascikj** [comment]
You can remove them by disabling the imdone-atom package setting **Show Tags Inline**
