### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by martindsouza** [imdone/imdone-core#6]
In a `.pkb` file (Oracle) I have the following TODOs:

```plsql
-- TODO test
-- TODO: test
```

When I run the shortcut `ctrl+shift+t` I just get an empty screen (image below). Is their any other configuration that is required?

![snip20150807_25](https://cloud.githubusercontent.com/assets/2925726/9137531/8c0da008-3cdb-11e5-95f0-effd6ed4795c.png)

**Comment by piascikj** [comment]
What version of imdone-atom are you on?  It should be in version 1.1.10 or above.  Try upgrading to the most recent version and let me know what you see.

**Comment by martindsouza** [comment]
I realize what that I was doing something wrong. I was trying to open imdone from a file rather than a project. It works now, thanks.
