### ISSUE TITLE
Dragging a task on the board removes the todo.txt-format "due:" tag

### ISSUE THREAD

**Issue by jm-welch** [imdone/imdone-core#82]
## Version
* Atom 1.18.0 (Mac)
* Imdone-atom 2.2.6

## Expected behavior
When a task contains a todo.txt-formatted metadata tag, such as `due:2017-06-21`, it should be preserved when the item is dragged on the imdone Task Board, regardless of the type of entry it represents.

## Observed behavior
The `due:<date>` tag is removed on drag. Custom tags are not impacted.

## Reproduction

1. Create a test file and add a `#TODO:` item with a due date using todo.txt format and a custom tag
    **test.file**
    ```
    #TODO: Demonstrate that tags fall off of tasks when moved on the board +imdone due:2017-06-21 foo:bar
    ```
2. View the task board to confirm that the task was created and that the tags are properly assigned
![image](https://user-images.githubusercontent.com/2350638/27397047-a26e2646-567a-11e7-8e79-dcc1d0144060.png)

3. Click and drag the tasks's card anywhere - reorder within the same column or move to another column
4. Confirm result:
    **test.file**
    ```
    #WIP:0 Demonstrate that tags fall off of tasks when moved on the board +imdone foo:bar
    ```
    
    ![image](https://user-images.githubusercontent.com/2350638/27397057-af26cda2-567a-11e7-860a-dd063a78110e.png)

**Comment by piascikj** [comment]
I believe this is fixed.  Can you please confirm?
